// Généré depuis l'export Airtable "Plan action nouveau client".
// Bibliothèque des actions standards ISO 9001 (démarrage SMQ) injectées à la
// création d'un client (CDC Module 5 / Annexe B).

export type ActionStandard = {
  ordre: number;
  descriptionCourte: string;
  actionAMener: string;
  indicateur: string | null;
  referenceIso: string[];
  priorite: "p1" | "p2" | "p3";
  type: "preventive" | "corrective";
};

export const ACTIONS_STANDARDS: ActionStandard[] = [
  {
    ordre: 1,
    descriptionCourte: "Création du SMQ : arborescence documentaire pour ranger les documents",
    actionAMener:
      "Création du SMQ : arboressence documentaire pour ranger chaque documents de manière à ce qu'ils soient facilement retrouvés par tous",
    indicateur: "% docs rangés selon arborescence",
    referenceIso: ["7.5"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 2,
    descriptionCourte: "Création d'une procédure de maîtrise documentaire",
    actionAMener:
      "Création d'une procédure de maitrise documentaire avec les règles de codifications des documents du système + les règles de gestion de modifications du SMQ (conséquences évaluées et responsabilités attribuées)",
    indicateur: "Procédure publiée et approuvée",
    referenceIso: ["7.5"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 3,
    descriptionCourte: "Fichier Excel de suivi des documents (procédures, modes opératoires...)",
    actionAMener:
      "Création d'un fichier Excel de suivi des documents ; procédures, documents, modes opératoires à jour…",
    indicateur: "Liste maîtresse unique à jour mensuellement",
    referenceIso: ["7.5"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 4,
    descriptionCourte: "Codification (code + date + version) pour chaque document",
    actionAMener:
      "Création d'une codification pour chaque document. Sur chaque document il devra y avoir (code + date de dernière mise à jour + version (A, B ... ou V1, V2...) d'après la procédure de maîtrise documentaire",
    indicateur: "% documents conformes à la codification",
    referenceIso: ["7.5"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 5,
    descriptionCourte: "Plan d'actions d'amélioration centralisant toutes les actions du SMQ",
    actionAMener:
      "Création d'un plan d'actions d'amélioration qui devra être composé de l'intégralité des actions du système (plan d'action issu de la revue de direction, actions issues de l'analyse des risques et opportunités, actions issues des audits, des revues de processus, du tableau de bord d'indicateur...)",
    indicateur: "% création du plan d'actions",
    referenceIso: ["6.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 6,
    descriptionCourte: "Fichier de planification des modifications du SMQ",
    actionAMener:
      "Création d'un fichier de planification des modifications / mises à jour du SMQ à venir",
    indicateur: "Tableau de planification 6.3 publié",
    referenceIso: ["6.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 7,
    descriptionCourte: "Fichier Excel de planification pour atteindre les objectifs qualité",
    actionAMener:
      "Création d'un fichier Excel de planification pour atteindre les objectifs qualité fixés par la direction",
    indicateur: "Plan d'atteinte des objectifs publié",
    referenceIso: ["6.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 8,
    descriptionCourte: "Manuel qualité intégrant les exclusions des chapitres 7.1.5 & 8.3",
    actionAMener: "Création du manuel qualité intégrant les exclusions des chapitres : 7.1.5 & 8.3",
    indicateur: "Manuel qualité finalisé V1",
    referenceIso: ["4.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 9,
    descriptionCourte: "Politique qualité datée et signée par la direction",
    actionAMener: "Création de la politique qualité (doit être datée, signée par la direction)",
    indicateur: "Politique qualité signée et diffusée",
    referenceIso: ["5.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 10,
    descriptionCourte: "Objectifs qualité SMART alignés avec la stratégie",
    actionAMener:
      "Création des objectifs qualité alignés avec la stratégie de l'entreprise. Datés et signés par la direction",
    indicateur: "Objectifs SMART validés en revue de direction",
    referenceIso: ["5.1.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 11,
    descriptionCourte: "Tableau de bord qualité avec objectifs SMART documentés",
    actionAMener:
      "Création d'un tableau de bord qualité avec les objectifs qualité SMART documentés",
    indicateur: "Tableau de bord qualité publié et mis à jour",
    referenceIso: ["6.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 12,
    descriptionCourte: "Communiquer la politique qualité aux parties intéressées",
    actionAMener:
      "Communiquer la politique qualité à toutes les parties intéressées pertinentes (collaborateurs, clients, fournisseurs)",
    indicateur: "Preuves de communication archivées",
    referenceIso: ["5.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 13,
    descriptionCourte: "Afficher la politique qualité dans les locaux",
    actionAMener: "Afficher la politique qualité dans les locaux",
    indicateur: "Affichage présent sur tous les sites",
    referenceIso: ["5.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 14,
    descriptionCourte: "Publier la politique qualité sur site web / intranet",
    actionAMener: "Publier la politique qualité sur site web / intranet",
    indicateur: "Politique publiée sur site web",
    referenceIso: ["5.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 15,
    descriptionCourte: "Sensibiliser les collaborateurs à la politique, objectifs et contribution",
    actionAMener:
      "Sensibiliser les collaborateurs à la politique qualité, aux objectifs, à leur contribution et aux conséquences en cas de non-respect",
    indicateur: "% collaborateurs sensibilisés à la politique qualité",
    referenceIso: ["7.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 16,
    descriptionCourte: "Cartographie des processus (pilotage, réalisation, support)",
    actionAMener:
      "Création de la cartographie des processus (processus de pilotage, de réalisation et support)",
    indicateur: "Cartographie processus publiée",
    referenceIso: ["4.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 17,
    descriptionCourte: "Désigner un pilote pour chaque processus",
    actionAMener:
      "Pour chaque processus : désigner un pilote de processus qui sera le garant de la performance du processus",
    indicateur: "100% processus avec pilote nommé",
    referenceIso: ["4.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 18,
    descriptionCourte: "Fiche d'identité pour chaque processus",
    actionAMener:
      "Pour chaque processus : créer une fiche d'identité (exemple : objectif, périmètre, indicateurs, entrées, sorties, ressources, pilote, contributeurs)",
    indicateur: "% processus avec fiche d'identité",
    referenceIso: ["4.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 19,
    descriptionCourte: "Revue annuelle de chaque processus avec son pilote",
    actionAMener:
      "Pour chaque processus : effectuer chaque année une revue de processus avec le pilote (avant la revue de direction)",
    indicateur: "Revues de processus réalisées avant RDD",
    referenceIso: [],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 20,
    descriptionCourte: "Tableau de bord de suivi des KPI pour chaque processus",
    actionAMener: "Créer un tableau de bord de suivi des KPI pour chaque processus (dont le SMQ)",
    indicateur: "Tableau de bord KPI processus publié",
    referenceIso: [],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 21,
    descriptionCourte: "Registre des risques et opportunités par processus",
    actionAMener:
      "Créer un registre des risques et des opportunités (pour chaque processus) en tenant compte des enjeux internes et externes, des parties intéressées",
    indicateur: "Registre R&O par processus publié",
    referenceIso: ["6.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 22,
    descriptionCourte: "Reporter et suivre les actions R&O dans le plan d'action",
    actionAMener:
      "Registre des risques et des opportunités (par processus) - Reporter chaque action issue du registre dans le plan d'actions d'amélioration",
    indicateur: "% actions R&O reportées et suivies",
    referenceIso: ["6.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 23,
    descriptionCourte: "Analyse des enjeux externes et internes (SWOT / PESTEL)",
    actionAMener:
      "Effectuer une analyse des enjeux externes et internes pertinents (SWOT et/ou PESTEL). Documenté, mis à jour annuellement",
    indicateur: "Analyse de contexte publiée et revue annuellement",
    referenceIso: ["4.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 24,
    descriptionCourte: "Registre des parties intéressées internes / externes",
    actionAMener:
      "Création du registre des parties intéressées Internes / Externes (clients, sous-traitants, fournisseurs, collaborateurs, autorités)",
    indicateur: "Registre PI publié et signé",
    referenceIso: ["4.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 25,
    descriptionCourte: "Fichier de veille réglementaire à mettre à jour",
    actionAMener:
      "Création d'un fichier de veille réglementaire (le mettre à jour à chaque évolution réglementaire pertinente)",
    indicateur: "Veille réglementaire complète à jour",
    referenceIso: ["5.1.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 26,
    descriptionCourte: "Procédure de veille réglementaire",
    actionAMener: "Création d'une procédure de veille réglementaire",
    indicateur: "Procédure veille publiée",
    referenceIso: ["5.1.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 27,
    descriptionCourte: "Procédure de gestion des enquêtes de satisfaction",
    actionAMener: "Création d'une procédure de gestion des enquêtes de satisfaction",
    indicateur: "Procédure satisfaction client publiée",
    referenceIso: ["9.1.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 28,
    descriptionCourte: "Mettre en place des enquêtes de satisfaction client",
    actionAMener: "Mettre en place des enquêtes de satisfaction client",
    indicateur: "1ère enquête réalisée + taux de réponse",
    referenceIso: ["9.1.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 29,
    descriptionCourte: "Analyser les résultats des enquêtes de satisfaction",
    actionAMener:
      "Suivre et analyser les résultats des enquêtes de satisfaction (avec déclenchement d'actions si besoin)",
    indicateur: "Rapport d'analyse satisfaction",
    referenceIso: ["9.1.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 30,
    descriptionCourte: "Communiquer les rapports satisfaction aux parties intéressées",
    actionAMener: "Communiquer les rapports des enquêtes de satisfaction aux parties intéressées",
    indicateur: "Communication réalisée et tracée",
    referenceIso: [],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 31,
    descriptionCourte: "Registre de suivi des réclamations",
    actionAMener:
      "Création d'un registre de suivi des réclamations (avec déclenchement d'actions si besoin)",
    indicateur: "Registre réclamations actif",
    referenceIso: ["9.1.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 32,
    descriptionCourte: "Organigramme avec rôles et fonction QSE",
    actionAMener: "Création d'un organigramme clair avec les rôles de chacun, dont la fonction QSE",
    indicateur: "Organigramme à jour avec fonction QSE",
    referenceIso: ["5.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 33,
    descriptionCourte: "Fiches de postes pour les fonctions clés (dont QSE)",
    actionAMener: "Création de fiches de postes pour les fonctions clés, dont la fonction QSE",
    indicateur: "% fonctions clés avec fiche de poste",
    referenceIso: ["5.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 34,
    descriptionCourte: "Lettre de mission du responsable qualité signée",
    actionAMener:
      "Création d'une lettre de mission du responsable qualité (ou fonction équivalente) signée par la direction",
    indicateur: "Lettre de mission RSMQ signée",
    referenceIso: ["5.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 35,
    descriptionCourte: "DUERP à jour annuellement",
    actionAMener: "Création d'un DUERP. Ce document doit être mis à jour chaque année",
    indicateur: "DUERP à jour",
    referenceIso: [],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 36,
    descriptionCourte: "Programme d'audit interne annuel (cycle 3 ans)",
    actionAMener:
      "Création d'un programme d'audit interne annuel (couvrant à minima 3 ans - cycle de certification)",
    indicateur: "Programme audit 3 ans publié",
    referenceIso: ["9.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 37,
    descriptionCourte: "Procédure d'audit interne",
    actionAMener: "Création d'une procédure d'audit interne",
    indicateur: "Procédure audit interne publiée",
    referenceIso: ["9.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 38,
    descriptionCourte: "Conserver et faire approuver les rapports d'audit par la direction",
    actionAMener: "Conserver les rapports d'audit + les faire approuver par la direction",
    indicateur: "Rapport audit blanc validé par DG",
    referenceIso: ["9.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 39,
    descriptionCourte: "Reporter les actions d'audit dans le plan d'amélioration",
    actionAMener:
      "Inclure dans le plan d'action d'amélioration les actions sortant des rapports d'audit interne",
    indicateur: "100% actions audit reportées",
    referenceIso: ["9.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 40,
    descriptionCourte: "Procédure de maîtrise des non-conformités et actions correctives",
    actionAMener:
      "Création d'une procédure de maîtrise des Non-Conformités et Actions Correctives couvrant le périmètre SMQ",
    indicateur: "Procédure étendue au périmètre SMQ",
    referenceIso: ["10.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 41,
    descriptionCourte: "Analyse des causes pour chaque NC + actions correctives",
    actionAMener:
      "Réaliser une analyse des causes pour chaque NC, actions correctives (à faire approuver par la direction)",
    indicateur: "% NC avec analyse causes documentée",
    referenceIso: ["10.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 42,
    descriptionCourte: "Fiches méthodologiques d'analyse des causes",
    actionAMener:
      "Création de fiches méthodologiques pour permettre à tous de faire une analyse des causes correcte (5 pourquoi, Ishikawa, etc.)",
    indicateur: "Fiches méthodologiques publiées",
    referenceIso: ["10.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 43,
    descriptionCourte: "Fiche NC modèle mise à disposition de tous",
    actionAMener:
      "Création d'une fiche de NC mise à dispositon de tous pour leur permettre de faire remonter les NC",
    indicateur: "Fiche NC modèle disponible",
    referenceIso: ["10.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 44,
    descriptionCourte: "Planifier et réaliser la revue de direction annuelle",
    actionAMener:
      "Planifier / réaliser une revue de direction chaque année (sur les données de l'année N-1). Inclure toutes les entrées obligatoires de la norme",
    indicateur: "1ère revue de direction réalisée",
    referenceIso: ["9.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 45,
    descriptionCourte: "Reporter les sorties RDD dans le plan d'action",
    actionAMener:
      "Reporter les éléments de sorties de la revue de direction dans le plan d'action d'amélioration",
    indicateur: "% sorties RDD reportées",
    referenceIso: ["9.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 46,
    descriptionCourte: "Procédures métiers pour chaque processus identifié",
    actionAMener:
      "Création de procédures métiers pour chaque processus identifié (exemple : procédure ADV, recrutement, mise en mission, etc.)",
    indicateur: "% processus avec procédure formelle",
    referenceIso: ["8.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 47,
    descriptionCourte: "Plan annuel de communication interne / externe",
    actionAMener:
      "Création d'un plan annuel de communication interne / externe. Conserver les preuves",
    indicateur: "Plan de communication publié",
    referenceIso: ["7.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 48,
    descriptionCourte: "Procédure d'organisation de l'animation et de la communication",
    actionAMener: "Création d'une procédure 'organisation de l'animation et de la communication'",
    indicateur: "Procédure animation/com publiée",
    referenceIso: ["7.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 49,
    descriptionCourte: "Grille d'évaluation des fournisseurs / prestataires",
    actionAMener:
      "Création d'une grille d'évaluation des fournisseurs. Liste des prestataires qualifiés mise à jour",
    indicateur: "Grille + liste prestataires en place",
    referenceIso: ["8.4.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 50,
    descriptionCourte: "Enquête de satisfaction collaborateur + plan d'action",
    actionAMener:
      "Création d'une enquête de satisfaction collaborateur (suivre, analyser les résultats, déclencher des actions)",
    indicateur: "1ère enquête réalisée + plan d'action",
    referenceIso: ["7.1.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 51,
    descriptionCourte: "Procédure de visite sécurité",
    actionAMener: "Création d'une procédure de visite sécurité",
    indicateur: "Procédure visite sécurité publiée",
    referenceIso: ["7.1.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 52,
    descriptionCourte: "Réaliser les visites sécurité des managers en mission",
    actionAMener:
      "Réaliser / faire réaliser aux managers les visites sécurité (surveillance de la sécurité sur site client)",
    indicateur: "% missions avec visite sécurité tracée",
    referenceIso: ["7.1.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 53,
    descriptionCourte: "Procédure d'élaboration / gestion des plans de prévention",
    actionAMener: "Création d'une procédure d'élaboration / gestion des plans de prévention",
    indicateur: "Procédure PDP publiée",
    referenceIso: ["7.1.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 54,
    descriptionCourte: "Mettre en place et gérer les plans de prévention par prestation",
    actionAMener: "Mettre en place et gérer les plans de prévention pour chaque prestation",
    indicateur: "100% missions avec PDP à jour",
    referenceIso: ["7.1.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 55,
    descriptionCourte: "Procédure d'accueil des nouveaux embauchés",
    actionAMener: "Création d'une procédure d'accueil des nouveaux embauchés",
    indicateur: "Procédure d'accueil unique publiée",
    referenceIso: ["7.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 56,
    descriptionCourte: "Procédure de suivi des prestations",
    actionAMener: "Création d'une procédure de suivi des prestations",
    indicateur: "Procédure suivi prestations publiée",
    referenceIso: ["7.1.6"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 57,
    descriptionCourte: "Procédure d'organisation de la formation des collaborateurs",
    actionAMener: "Création d'une procédure sur l'organisation de la formation des collaborateurs",
    indicateur: "Procédure formation globale publiée",
    referenceIso: ["7.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 58,
    descriptionCourte: "Matrice des compétences + conservation des diplômes",
    actionAMener:
      "Création d'une matrice des compétences (avec conservation des diplômes des collaborateurs)",
    indicateur: "Matrice des compétences groupe",
    referenceIso: ["7.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 59,
    descriptionCourte: "Plan de formation, évaluation post-formation, entretiens annuels",
    actionAMener: "Création d'un plan de formation, évaluation post-formation, entretiens annuels",
    indicateur: "Plan formation N+1 + % évaluations post-formation",
    referenceIso: ["7.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 60,
    descriptionCourte: "Inventaire infrastructure + plan de maintenance",
    actionAMener:
      "Conserver pour chaque infrastructure (bâtiments, équipements, SI, transport) : inventaire, plan de maintenance, suivi des contrôles",
    indicateur: "Registre équipements + plan maintenance",
    referenceIso: ["7.1.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 61,
    descriptionCourte: "Procédure de gestion du matériel",
    actionAMener: "Création d'une procédure de gestion du matériel",
    indicateur: "Procédure gestion matériel publiée",
    referenceIso: ["7.1.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 62,
    descriptionCourte: "Procédure de gestion des réclamations + registre",
    actionAMener: "Création d'une procédure de gestion des réclamations",
    indicateur: "Procédure réclamations + registre",
    referenceIso: ["8.2.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 63,
    descriptionCourte: "Modèle de proposition technique et financière (PTF/devis)",
    actionAMener:
      "Voir si le modèle de proposition technique et financière (devis / offre) informe correctement le client de toutes les exigences",
    indicateur: "Modèle PTF déployé",
    referenceIso: ["8.2.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 64,
    descriptionCourte: "Vérifier identification des exigences clients dans revue d'offre",
    actionAMener:
      "Vérifier que les exigences clients (y compris légales/réglementaires) sont identifiées lors de la revue d'offre",
    indicateur: "Modèle revue d'offre publié",
    referenceIso: ["8.2.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 65,
    descriptionCourte: "Vérifier que les écarts exigences client / capacités sont résolus",
    actionAMener:
      "Vérifier que les écarts entre exigences client et capacités de l'organisme sont identifiés et résolus avant signature",
    indicateur: "Procédure revue d'offre incluant résolution écarts",
    referenceIso: ["8.2.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 66,
    descriptionCourte: "Procédure de gestion des achats / sous-traitance",
    actionAMener: "Création d'une procédure de gestion des achats / de la sous-traitance",
    indicateur: "Procédure achats/sous-traitance publiée",
    referenceIso: ["8.4.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 67,
    descriptionCourte: "Cahier des charges fournisseurs avec exigences qualité",
    actionAMener:
      "Conserver les cahiers des charges fournisseurs ; contrats avec exigences qualité",
    indicateur: "% fournisseurs avec CDC qualité",
    referenceIso: ["8.4.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 68,
    descriptionCourte: "Procédure d'identification et traçabilité des prestations",
    actionAMener:
      "Création d'une procédure d'identification et de traçabilité des prestations (codification des missions, suivi)",
    indicateur: "% missions avec traçabilité conforme",
    referenceIso: ["8.5.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 69,
    descriptionCourte: "Procédure de gestion de la propriété client + registre",
    actionAMener:
      "Création d'une procédure de gestion de la propriété client (données techniques, matériel prêté, etc.)",
    indicateur: "Procédure publiée + registre actif",
    referenceIso: ["8.5.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 70,
    descriptionCourte: "Procédure de préservation des livrables",
    actionAMener:
      "Création d'une procédure de préservation des livrables (sauvegarde, intégrité, archivage)",
    indicateur: "Procédure publiée",
    referenceIso: ["8.5.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 71,
    descriptionCourte: "Processus de suivi fin de mission (entretien, retour exp)",
    actionAMener:
      "Création d'un processus de suivi fin de mission (entretien de fin de mission, retour d'expérience)",
    indicateur: "% missions avec retour fin de mission",
    referenceIso: ["8.5.5"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 72,
    descriptionCourte: "Procédure de maîtrise des modifications en cours de prestation",
    actionAMener:
      "Création d'une procédure de maîtrise des modifications en cours de prestation (avenants, changements de périmètre)",
    indicateur: "Procédure publiée",
    referenceIso: ["8.5.6"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 73,
    descriptionCourte: "Plan de Continuité d'Activité (PCA) cyber validé et testé",
    actionAMener:
      "Création d'un Plan de Continuité d'Activité couvrant les risques cyber identifiés",
    indicateur: "PCA validé et testé",
    referenceIso: ["6.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 74,
    descriptionCourte: "Kick-off interne pour communiquer sur la démarche qualité",
    actionAMener:
      "Organiser un kick-off interne pour communiquer sur le démarrage de la démarche qualité et impliquer les équipes",
    indicateur: "Kick-off réalisé + taux de participation",
    referenceIso: ["7.4"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 75,
    descriptionCourte: "Évaluer le risque de dépendance aux fournisseurs critiques",
    actionAMener:
      "Évaluer le risque de dépendance aux fournisseurs critiques (outils métier, plateformes), prévoir un plan de secours",
    indicateur: "Liste fournisseurs critiques + plan de secours",
    referenceIso: ["8.4.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 76,
    descriptionCourte: "Analyser les données qualité (KPI, satisfaction, fournisseurs, NC)",
    actionAMener:
      "Analyser les données qualité (tendances KPI, conformité, satisfaction client, performance fournisseurs, efficacité actions correctives) en entrée de revue de direction",
    indicateur: "Rapport d'analyse mensuel/trimestriel publié",
    referenceIso: ["9.1.3"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 77,
    descriptionCourte: "Formaliser le processus de qualification des consultants techniques",
    actionAMener:
      "Formaliser les critères et le processus de qualification des consultants techniques (cœur de métier) : grille d'évaluation, validation BM/TA, références, contrôles techniques",
    indicateur: "% consultants qualifiés selon process",
    referenceIso: ["7.2"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 78,
    descriptionCourte: "Politique de sauvegarde et sécurité informatique RGPD compatible",
    actionAMener:
      "Formaliser une politique de sauvegarde et de sécurité informatique des données SMQ (RGPD compatible) : sauvegarde, accès, confidentialité, intégrité, durée de conservation",
    indicateur: "Politique IT/RGPD publiée",
    referenceIso: ["7.5"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 79,
    descriptionCourte: "Comité qualité périodique entre revues de direction",
    actionAMener:
      "Mettre en place un comité qualité périodique (mensuel ou trimestriel) avec direction, pilotes processus et référent QHSE pour piloter le SMQ entre deux revues de direction",
    indicateur: "Nb comités qualité réalisés/an",
    referenceIso: ["9.1"],
    priorite: "p1",
    type: "corrective",
  },
  {
    ordre: 80,
    descriptionCourte:
      "Décliner les objectifs qualité par fonction (BM, TA, Consultants, RH, Direction)",
    actionAMener:
      "Décliner les objectifs qualité globaux par fonction et niveau pertinent : BM, TA, Consultants, RH, Direction. Objectifs SMART individualisés",
    indicateur: "% fonctions avec objectifs qualité déclinés",
    referenceIso: ["6.2"],
    priorite: "p1",
    type: "corrective",
  },
];
