-- ============================================================================
-- Seed du référentiel MASE 2024 — AXES 2 à 5 (196 questions).
--
-- Suite du seed de l'Axe 1. Questions officielles transcrites du manuel MASE
-- 2024 (pp. 28-59) : Axe 2 (Compétences, 48 q.), Axe 3 (Organisation du travail,
-- 77 q.), Axe 4 (Efficacité, 51 q.), Axe 5 (Bilan & amélioration, 31 q.).
-- Points + cotation B/V/VD + neutralisation. Idempotent.
-- ============================================================================

insert into public.referentiel_iso
  (norme, version, chapitre, intitule, axe, points_max, cotation_type, neutralisable, est_obligatoire, ordre_affichage)
values
  ('MASE', '2024', '2.1.1', 'L''employeur a-t-il défini un dispositif de recrutement pour les postes de l''entreprise ?', 2, 10, 'B', false, true, 2000),
  ('MASE', '2024', '2.1.2', 'L''employeur a-t-il défini un dispositif similaire pour toute demande de personnel temporaire ?', 2, 10, 'B', false, true, 2001),
  ('MASE', '2024', '2.1.3', 'Ce dispositif prend-il en compte pour la tenue du poste de travail : les missions / tâches du poste ?', 2, 10, 'B', false, true, 2002),
  ('MASE', '2024', '2.1.4', 'Ce dispositif prend-il en compte : les compétences exigées ?', 2, 10, 'B', false, true, 2003),
  ('MASE', '2024', '2.1.5', 'Ce dispositif prend-il en compte : la sensibilité et les connaissances en matière de SSE ?', 2, 30, 'V', false, true, 2004),
  ('MASE', '2024', '2.1.6', 'Ce dispositif prend-il en compte : les aptitudes médicales nécessaires ?', 2, 10, 'B', false, true, 2005),
  ('MASE', '2024', '2.1.7', 'Ce dispositif prend-il en compte : les formations nécessaires ?', 2, 10, 'B', false, true, 2006),
  ('MASE', '2024', '2.1.8', 'Ce dispositif prend-il en compte : les autorisations / habilitations nécessaires ?', 2, 10, 'B', false, true, 2007),
  ('MASE', '2024', '2.1.9', 'Ce dispositif prend-il en compte : les restrictions réglementaires ?', 2, 10, 'B', false, true, 2008),
  ('MASE', '2024', '2.1.10', 'L''employeur a-t-il établi une liste des postes à risques particuliers ?', 2, 10, 'B', false, true, 2009),
  ('MASE', '2024', '2.1.11', 'Ce dispositif prévoit-il une évaluation de la sensibilité et des connaissances avant embauche dans le domaine : Sécurité ?', 2, 10, 'B', false, true, 2010),
  ('MASE', '2024', '2.1.12', 'Ce dispositif prévoit-il une évaluation avant embauche dans le domaine : Santé ?', 2, 10, 'B', false, true, 2011),
  ('MASE', '2024', '2.1.13', 'Ce dispositif prévoit-il une évaluation avant embauche dans le domaine : Environnement ?', 2, 10, 'B', false, true, 2012),
  ('MASE', '2024', '2.2.1.1', 'L''employeur a-t-il mis en place un dispositif d''accompagnement du personnel (parrain / tuteur) ?', 2, 10, 'B', false, true, 2013),
  ('MASE', '2024', '2.2.1.2', 'Ce dispositif d''accompagnement est-il appliqué pour tout nouvel arrivant ?', 2, 30, 'V', true, true, 2014),
  ('MASE', '2024', '2.2.1.3', 'Ce dispositif d''accompagnement est-il appliqué pour tout changement de poste de travail ?', 2, 15, 'V', true, true, 2015),
  ('MASE', '2024', '2.2.1.4', 'La désignation du parrain/tuteur prend-elle en compte : sa connaissance de l''entreprise ?', 2, 5, 'B', false, true, 2016),
  ('MASE', '2024', '2.2.1.5', 'La désignation du parrain/tuteur prend-elle en compte : ses compétences techniques ?', 2, 5, 'B', false, true, 2017),
  ('MASE', '2024', '2.2.1.6', 'La désignation du parrain/tuteur prend-elle en compte : sa sensibilité en matière de SSE et son adhésion au niveau d''exigence de l''entreprise dans ces domaines ?', 2, 15, 'V', false, true, 2018),
  ('MASE', '2024', '2.2.1.7', 'La désignation du parrain/tuteur prend-elle en compte : ses aptitudes pédagogiques ?', 2, 5, 'B', false, true, 2019),
  ('MASE', '2024', '2.2.1.8', 'Le parrain / tuteur connait-il ses missions ?', 2, 10, 'B', true, true, 2020),
  ('MASE', '2024', '2.2.1.9', 'La fin de période d''accompagnement est-elle actée ?', 2, 10, 'B', true, true, 2021),
  ('MASE', '2024', '2.2.2.1', 'Une formation « accueil SSE » est-elle dispensée à l''arrivée dans l''entreprise ?', 2, 10, 'B', true, true, 2022),
  ('MASE', '2024', '2.2.2.2', 'Une formation « accueil SSE » est-elle dispensée à la suite d''un changement de poste de travail / technique de travail ?', 2, 10, 'B', true, true, 2023),
  ('MASE', '2024', '2.2.2.3', 'Une formation « accueil SSE » est-elle dispensée à la suite d''une absence de longue durée (définie par la réglementation ou, à défaut, par l''employeur) ?', 2, 10, 'B', true, true, 2024),
  ('MASE', '2024', '2.2.2.4', 'Cette formation « accueil SSE » porte-t-elle sur : les risques SSE identifiés pour la réalisation des tâches / travaux / prestations ?', 2, 30, 'V', false, true, 2025),
  ('MASE', '2024', '2.2.2.5', 'Cette formation porte-t-elle sur : les précautions à prendre pour assurer sa propre sécurité, sa santé et la protection de l''environnement ?', 2, 30, 'V', false, true, 2026),
  ('MASE', '2024', '2.2.2.6', 'Cette formation porte-t-elle sur : la conduite à tenir en cas de situations dangereuses, de presqu''accidents ou d''accidents, impactant la sécurité, la santé ou l''environnement ?', 2, 10, 'B', false, true, 2027),
  ('MASE', '2024', '2.2.2.7', 'Cette formation porte-t-elle sur : des Retours d''Expérience (REx) notables et/ou récents dans les domaines SSE ?', 2, 30, 'VD', false, true, 2028),
  ('MASE', '2024', '2.2.2.8', 'L''employeur contrôle-t-il les connaissances acquises lors de l''accueil SSE ?', 2, 25, 'V', false, true, 2029),
  ('MASE', '2024', '2.2.2.9', 'Une formation renforcée est-elle déclinée au personnel concerné ?', 2, 5, 'B', true, true, 2030),
  ('MASE', '2024', '2.2.3.1', 'L''employeur coordonne-t-il l''ensemble des formations nécessaires à la tenue des postes de travail ?', 2, 50, 'V', false, true, 2031),
  ('MASE', '2024', '2.2.3.2', 'L''employeur a-t-il délivré une habilitation (travaux d''ordre électrique) ou une autorisation (permis de travaux, conduite de chariots, d''engins, de grues, travaux de levage…) pour les tâches le nécessitant ?', 2, 30, 'V', true, true, 2032),
  ('MASE', '2024', '2.2.3.3', 'Ces titres d''habilitations et autorisations sont-ils émis au regard de l''aptitude médicale, de la validité de la formation et de la connaissance des règles de sécurité du lieu d''intervention ?', 2, 10, 'B', true, true, 2033),
  ('MASE', '2024', '2.2.3.4', 'Ces titres d''habilitations et autorisations sont-ils émis pour l''intégralité du personnel concerné ?', 2, 20, 'V', true, true, 2034),
  ('MASE', '2024', '2.2.3.5', 'L''employeur coordonne-t-il le recyclage des formations et le renouvellement de l''habilitation et des autorisations pour l''intégralité du personnel ?', 2, 25, 'V', false, true, 2035),
  ('MASE', '2024', '2.2.3.6', 'L''employeur coordonne-t-il le renouvellement des aptitudes médicales ?', 2, 20, 'V', true, true, 2036),
  ('MASE', '2024', '2.2.3.7', 'L''employeur s''assure-t-il que les aptitudes médicales/restrictions de l''intégralité du personnel sont en adéquation avec les besoins du poste confié ?', 2, 10, 'B', false, true, 2037),
  ('MASE', '2024', '2.2.3.8', 'L''employeur s''assure-t-il de l''acquisition des connaissances SSE des personnels organiques ?', 2, 25, 'V', true, true, 2038),
  ('MASE', '2024', '2.2.3.9', 'L''employeur s''assure-t-il de l''acquisition des connaissances SSE des personnels non-organiques ?', 2, 25, 'V', true, true, 2039),
  ('MASE', '2024', '2.3.1', 'L''employeur intègre-t-il la culture SSE dans tous les éléments de son système de management ?', 2, 50, 'VD', false, true, 2040),
  ('MASE', '2024', '2.3.2', 'La culture SSE est-elle présente à tous les niveaux de l''entreprise et pour l''intégralité du personnel (dont les nouveaux arrivants, les travailleurs temporaires) ?', 2, 30, 'VD', false, true, 2041),
  ('MASE', '2024', '2.3.3', 'Cette culture couvre le domaine : Sécurité ?', 2, 10, 'B', false, true, 2042),
  ('MASE', '2024', '2.3.4', 'Cette culture couvre le domaine : Santé ?', 2, 10, 'B', false, true, 2043),
  ('MASE', '2024', '2.3.5', 'Cette culture couvre le domaine : Environnement ?', 2, 10, 'B', false, true, 2044),
  ('MASE', '2024', '2.3.6', 'L''employeur évalue-t-il cette culture pour l''ensemble des personnels dans le domaine : Sécurité ?', 2, 20, 'V', true, true, 2045),
  ('MASE', '2024', '2.3.7', 'L''employeur évalue-t-il cette culture dans le domaine : Santé ?', 2, 20, 'V', true, true, 2046),
  ('MASE', '2024', '2.3.8', 'L''employeur évalue-t-il cette culture dans le domaine : Environnement ?', 2, 20, 'V', true, true, 2047),
  ('MASE', '2024', '3.1.1', 'La méthode d''analyse des risques est-elle formalisée ?', 3, 10, 'B', false, true, 3000),
  ('MASE', '2024', '3.1.2', 'La méthode utilisée est-elle maitrisée par la (ou les) personne(s) en charge de la mettre en œuvre ?', 3, 10, 'B', false, true, 3001),
  ('MASE', '2024', '3.1.3', 'La méthode utilisée intègre-t-elle une visite des lieux de travail ?', 3, 10, 'B', false, true, 3002),
  ('MASE', '2024', '3.1.4', 'L''analyse des risques intègre-t-elle le domaine : Sécurité ?', 3, 10, 'B', false, true, 3003),
  ('MASE', '2024', '3.1.5', 'L''analyse des risques intègre-t-elle le domaine : Santé ?', 3, 10, 'B', false, true, 3004),
  ('MASE', '2024', '3.1.6', 'L''analyse des risques intègre-t-elle le domaine : Environnement ?', 3, 10, 'B', false, true, 3005),
  ('MASE', '2024', '3.1.7', 'L''ensemble des personnes qui interviennent pour l''entreprise sont-elles couvertes par une (ou des) analyse(s) de risques SSE ?', 3, 50, 'V', false, true, 3006),
  ('MASE', '2024', '3.1.8', 'L''(les) analyse(s) de risques SSE concerne(nt)-t-elle(s) l''ensemble des activités de l''entreprise ?', 3, 50, 'V', false, true, 3007),
  ('MASE', '2024', '3.1.9', 'L''employeur a-t-il sollicité les compétences nécessaires (internes et/ou externes) à l''élaboration de (ou des) l''analyse(s) de risques SSE ?', 3, 10, 'B', false, true, 3008),
  ('MASE', '2024', '3.1.10', 'L''employeur a-t-il pris en compte les informations nécessaires à l''élaboration des analyses de risques SSE (nature des tâches/travaux/prestations, risques/dangers, aspects/impacts…) ?', 3, 40, 'V', false, true, 3009),
  ('MASE', '2024', '3.1.11', 'L''(les) analyse(s) de risques SSE est (sont)-elle(s) appliquée(s) pour l''intégralité des tâches, travaux ou prestations qu''il a à réaliser ?', 3, 40, 'V', false, true, 3010),
  ('MASE', '2024', '3.1.12', 'L''(les) analyse(s) de risques SSE impacte(nt)-t-elle(s) la préparation des tâches, travaux ou prestations ?', 3, 50, 'V', false, true, 3011),
  ('MASE', '2024', '3.1.13', 'Les principes généraux de prévention ont-ils été appliqués pour établir les mesures de prévention issues des analyses des risques sécurité-santé ?', 3, 80, 'V', false, true, 3012),
  ('MASE', '2024', '3.1.14', 'Les principes fondamentaux environnementaux ont-ils été appliqués pour établir les mesures de prévention issues des analyses des risques pour l''environnement ?', 3, 50, 'V', false, true, 3013),
  ('MASE', '2024', '3.1.15', 'Les modifications des conditions opératoires entrainent-elles une révision des analyses des risques SSE et moyens de prévention associés ?', 3, 25, 'VD', false, true, 3014),
  ('MASE', '2024', '3.2.1', 'La planification des tâches, travaux ou prestations prend-elle en compte : toutes les phases d''activités ?', 3, 10, 'B', false, true, 3015),
  ('MASE', '2024', '3.2.2', 'La planification prend-elle en compte : les moyens humains (internes et externes) ?', 3, 10, 'B', false, true, 3016),
  ('MASE', '2024', '3.2.3', 'La planification prend-elle en compte : les moyens matériels/matériaux adaptés (internes et externes) ?', 3, 10, 'B', false, true, 3017),
  ('MASE', '2024', '3.2.4', 'La planification prend-elle en compte : les compétences, aptitudes médicales, formations, autorisations/habilitations ?', 3, 10, 'B', false, true, 3018),
  ('MASE', '2024', '3.2.5', 'La planification prend-elle en compte les mesures de prévention associées aux risques identifiés : Sécurité ?', 3, 10, 'B', false, true, 3019),
  ('MASE', '2024', '3.2.6', 'La planification prend-elle en compte les mesures de prévention : Santé ?', 3, 10, 'B', false, true, 3020),
  ('MASE', '2024', '3.2.7', 'La planification prend-elle en compte les mesures de prévention : Environnement ?', 3, 10, 'B', false, true, 3021),
  ('MASE', '2024', '3.2.8', 'Les modes opératoires définissent-ils : les tâches précises à réaliser ?', 3, 5, 'B', false, true, 3022),
  ('MASE', '2024', '3.2.9', 'Les modes opératoires définissent-ils : leur ordre/phasage/chronologie (y compris la fin de chantier) ?', 3, 5, 'B', false, true, 3023),
  ('MASE', '2024', '3.2.10', 'Les modes opératoires définissent-ils : les points d''arrêts ?', 3, 10, 'B', false, true, 3024),
  ('MASE', '2024', '3.2.11', 'Les modes opératoires définissent-ils : les matériels utilisés ?', 3, 5, 'B', false, true, 3025),
  ('MASE', '2024', '3.2.12', 'Les modes opératoires définissent-ils : les produits utilisés ?', 3, 5, 'B', false, true, 3026),
  ('MASE', '2024', '3.2.13', 'Dans le cadre de la préparation d''équipements de travail et de matériel, l''employeur s''assure-t-il de la conformité : réglementaire ?', 3, 5, 'B', false, true, 3027),
  ('MASE', '2024', '3.2.14', 'L''employeur s''assure-t-il de la conformité : à l''expression du besoin initial ?', 3, 5, 'B', false, true, 3028),
  ('MASE', '2024', '3.2.15', 'L''employeur s''assure-t-il de la conformité : aux exigences du client ?', 3, 5, 'B', true, true, 3029),
  ('MASE', '2024', '3.2.16', 'L''employeur s''assure-t-il de la conformité des documents réglementaires (notices constructeur, certificat de conformité, rapport de vérifications périodiques, assurances, carnet de maintenance…) ?', 3, 5, 'B', false, true, 3030),
  ('MASE', '2024', '3.2.17', 'Dans le cadre du prêt de matériel à d''autres entreprises, une convention a-t-elle été rédigée ?', 3, 5, 'B', true, true, 3031),
  ('MASE', '2024', '3.2.18', 'Les modifications des conditions opératoires entrainent-elles une révision de la préparation ?', 3, 25, 'V', false, true, 3032),
  ('MASE', '2024', '3.2.19', 'Dans le cadre de recours à la sous-traitance : l''employeur a-t-il défini un dispositif de sélection SSE de ses sous-traitants ?', 3, 5, 'B', false, true, 3033),
  ('MASE', '2024', '3.2.20', 'Ce dispositif prévoit-il la transmission des exigences SSE (internes et clients) ?', 3, 5, 'B', false, true, 3034),
  ('MASE', '2024', '3.2.21', 'Les sous-traitants retenus possèdent-ils un système certifié MASE/FC (ou équivalent) ou en cours de certification ? Le cas échéant, des mesures compensatoires sont-elles mises en place ?', 3, 10, 'B', true, true, 3035),
  ('MASE', '2024', '3.2.22', 'Dans le cas où des mesures compensatoires sont mises en place, ces dernières sont-elles adaptées ?', 3, 50, 'V', true, true, 3036),
  ('MASE', '2024', '3.2.23', 'Dans le cadre d''une intervention sur site client, l''employeur a-t-il pris en compte les exigences particulières du client ?', 3, 50, 'V', true, true, 3037),
  ('MASE', '2024', '3.2.24', 'L''employeur met-il à disposition de son personnel les locaux de vie et installations conformes aux exigences réglementaires ?', 3, 10, 'B', true, true, 3038),
  ('MASE', '2024', '3.2.25', 'Dans le cadre d''une intervention en dehors de ses locaux, l''employeur s''assure-t-il de la mise à disposition de locaux de vie et d''installations conformes aux exigences réglementaires ?', 3, 25, 'V', true, true, 3039),
  ('MASE', '2024', '3.3.1', 'Le planning des tâches, travaux ou prestations fait-il l''objet d''un suivi tout au long de la réalisation ?', 3, 10, 'B', false, true, 3040),
  ('MASE', '2024', '3.3.2', 'La mise au travail est-elle réalisée ?', 3, 10, 'B', false, true, 3041),
  ('MASE', '2024', '3.3.3', 'Les modes opératoires sont-ils disponibles sur le lieu des tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3042),
  ('MASE', '2024', '3.3.4', 'Les analyses des risques sont-elles disponibles sur le lieu des tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3043),
  ('MASE', '2024', '3.3.5', 'Les moyens de prévention définis sont-ils communiqués aux personnels ?', 3, 10, 'B', false, true, 3044),
  ('MASE', '2024', '3.3.6', 'Les moyens de prévention définis sont-ils compris ?', 3, 10, 'B', false, true, 3045),
  ('MASE', '2024', '3.3.7', 'Les moyens de prévention définis sont-ils appliqués ?', 3, 100, 'V', false, true, 3046),
  ('MASE', '2024', '3.3.8', 'La correspondance entre la préparation et les conditions d''exécution des tâches, travaux ou prestations a-t-elle été vérifiée ?', 3, 10, 'B', true, true, 3047),
  ('MASE', '2024', '3.3.9', 'En cas de relève ou d''affectation de nouveau personnel, l''employeur s''assure-t-il de la continuité des informations ?', 3, 10, 'B', true, true, 3048),
  ('MASE', '2024', '3.3.10', 'Les moyens humains (internes et externes) sont-ils en adéquation avec les tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3049),
  ('MASE', '2024', '3.3.11', 'Les compétences nécessaires sont-elles en adéquation avec les tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3050),
  ('MASE', '2024', '3.3.12', 'Les autorisations/habilitations nécessaires sont-elles en adéquation avec les tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3051),
  ('MASE', '2024', '3.3.13', 'En cas de recours à du personnel temporaire, l''employeur informe-t-il l''agence d''emploi de toute modification de la mission initialement prévue ?', 3, 10, 'B', true, true, 3052),
  ('MASE', '2024', '3.3.14', 'Les moyens matériels sont-ils en adéquation avec les tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3053),
  ('MASE', '2024', '3.3.15', 'Les équipements de travail sont-ils mis en œuvre conformément aux prescriptions/notices du constructeur ?', 3, 10, 'B', false, true, 3054),
  ('MASE', '2024', '3.3.16', 'Les documents réglementaires sont-ils disponibles sur le lieu des tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3055),
  ('MASE', '2024', '3.3.17', 'Les équipements de travail sont-ils maintenus en bon état ?', 3, 40, 'V', false, true, 3056),
  ('MASE', '2024', '3.3.18', 'Les moyens organisationnels (organisation du personnel du chantier, risques d''interférences et/ou de coactivité, moyens de prévention associés) sont-ils en adéquation avec les tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3057),
  ('MASE', '2024', '3.3.19', 'Les contrôles des niveaux d''exposition du personnel sont-ils réalisés ?', 3, 20, 'VD', false, true, 3058),
  ('MASE', '2024', '3.3.20', 'Les moyens liés à la préservation de l''environnement sont-ils appliqués ?', 3, 20, 'VD', false, true, 3059),
  ('MASE', '2024', '3.3.21', 'L''employeur vérifie-t-il que son sous-traitant respecte les exigences requises en matière SSE ?', 3, 10, 'B', true, true, 3060),
  ('MASE', '2024', '3.3.22', 'L''employeur a-t-il déclaré aux parties intéressées (EU, coordonnateur SPS…) la totalité de ses sous-traitants ?', 3, 5, 'B', true, true, 3061),
  ('MASE', '2024', '3.3.23', 'L''employeur a-t-il un dispositif de fin de tâches/travaux/prestations ?', 3, 10, 'B', false, true, 3062),
  ('MASE', '2024', '3.3.24', 'Les modifications des conditions opératoires entrainent-elles une révision de la réalisation ?', 3, 25, 'VD', false, true, 3063),
  ('MASE', '2024', '3.4.1', 'L''employeur établit-il un bilan à l''issue des tâches, travaux ou prestations ?', 3, 10, 'B', false, true, 3064),
  ('MASE', '2024', '3.4.2', 'Ce bilan intègre-t-il : les remontées d''information du personnel ?', 3, 10, 'B', false, true, 3065),
  ('MASE', '2024', '3.4.3', 'Ce bilan intègre-t-il : les situations dangereuses, presqu''accidents et accidents ?', 3, 10, 'B', false, true, 3066),
  ('MASE', '2024', '3.4.4', 'Ce bilan intègre-t-il : les résultats des mesurages liés à la santé des travailleurs ?', 3, 10, 'B', false, true, 3067),
  ('MASE', '2024', '3.4.5', 'Ce bilan intègre-t-il : les impacts sur l''environnement ?', 3, 10, 'B', false, true, 3068),
  ('MASE', '2024', '3.4.6', 'Ce bilan intègre-t-il : les évaluations des sous-traitants et du personnel temporaire ?', 3, 10, 'B', false, true, 3069),
  ('MASE', '2024', '3.4.7', 'Ce bilan intègre-t-il : les constats suite aux audits/visites, contrôles (internes ou externes) ?', 3, 10, 'B', false, true, 3070),
  ('MASE', '2024', '3.4.8', 'Ce bilan intègre-t-il : les modifications des conditions opératoires et leur gestion ?', 3, 10, 'B', false, true, 3071),
  ('MASE', '2024', '3.4.9', 'Ce bilan met-il en évidence : les points positifs, les points à améliorer ?', 3, 5, 'B', false, true, 3072),
  ('MASE', '2024', '3.4.10', 'Ce bilan met-il en évidence : l''efficacité des analyses des risques et des modes opératoires ?', 3, 5, 'B', false, true, 3073),
  ('MASE', '2024', '3.4.11', 'Ce bilan met-il en évidence : les faits marquants ?', 3, 5, 'B', false, true, 3074),
  ('MASE', '2024', '3.4.12', 'Ce bilan met-il en évidence : les écarts entre l''analyse de la préparation (travail prescrit) et la réalisation (travail réel) ?', 3, 5, 'B', false, true, 3075),
  ('MASE', '2024', '3.4.13', 'La capitalisation du retour d''expérience permet-elle d''améliorer les pratiques de l''entreprise ?', 3, 50, 'VD', false, true, 3076),
  ('MASE', '2024', '4.1.1', 'L''employeur réalise-t-il un recueil des faits pour : les situations dangereuses ?', 4, 10, 'B', false, true, 4000),
  ('MASE', '2024', '4.1.2', 'L''employeur réalise-t-il un recueil des faits pour : les presqu''accidents ?', 4, 10, 'B', false, true, 4001),
  ('MASE', '2024', '4.1.3', 'L''employeur réalise-t-il un recueil des faits pour : les accidents ?', 4, 10, 'B', false, true, 4002),
  ('MASE', '2024', '4.1.4', 'L''employeur réalise-t-il un recueil des faits pour : les maladies professionnelles ?', 4, 10, 'B', false, true, 4003),
  ('MASE', '2024', '4.1.5', 'L''employeur réalise-t-il un recueil des faits pour : les impacts environnementaux ?', 4, 10, 'B', false, true, 4004),
  ('MASE', '2024', '4.1.6', 'L''employeur a-t-il défini un (des) seuil(s) au-delà duquel (desquels) il entreprend une analyse approfondie ?', 4, 10, 'B', false, true, 4005),
  ('MASE', '2024', '4.1.7', 'Le (ou les) critère(s) défini(s) sont-ils pertinents (gravité réelle, gravité potentielle, fréquence, occurrence/REX, maitrise) ?', 4, 50, 'VD', false, true, 4006),
  ('MASE', '2024', '4.1.8', 'L''employeur réalise-t-il, à l''aide d''une méthode, une analyse approfondie des faits pour : les situations dangereuses ?', 4, 10, 'B', false, true, 4007),
  ('MASE', '2024', '4.1.9', 'Analyse approfondie pour : les presqu''accidents ?', 4, 10, 'B', false, true, 4008),
  ('MASE', '2024', '4.1.10', 'Analyse approfondie pour : les accidents ?', 4, 10, 'B', false, true, 4009),
  ('MASE', '2024', '4.1.11', 'Analyse approfondie pour : les maladies professionnelles ?', 4, 10, 'B', false, true, 4010),
  ('MASE', '2024', '4.1.12', 'Analyse approfondie pour : les impacts environnementaux ?', 4, 10, 'B', false, true, 4011),
  ('MASE', '2024', '4.1.13', 'La méthode d''analyse approfondie est-elle maitrisée ?', 4, 10, 'B', false, true, 4012),
  ('MASE', '2024', '4.1.14', 'La mise en œuvre de la méthode d''analyse permet-elle de mettre en évidence des causes directes ?', 4, 25, 'V', false, true, 4013),
  ('MASE', '2024', '4.1.15', 'La mise en œuvre de la méthode d''analyse permet-elle de mettre en évidence des causes fondamentales ?', 4, 25, 'V', false, true, 4014),
  ('MASE', '2024', '4.1.16', 'La mise en œuvre de la méthode d''analyse permet-elle d''élaborer des actions pertinentes ?', 4, 50, 'V', false, true, 4015),
  ('MASE', '2024', '4.1.17', 'Ces actions sont-elles intégrées dans le plan d''actions SSE de l''entreprise ?', 4, 10, 'B', false, true, 4016),
  ('MASE', '2024', '4.1.18', 'L''employeur s''est-il assuré de la présence d''un dispositif équivalent chez ses sous-traitants ?', 4, 10, 'B', true, true, 4017),
  ('MASE', '2024', '4.1.19', 'Les actions menées à l''issue de l''analyse permettent-elles d''améliorer les résultats : Sécurité ?', 4, 10, 'B', false, true, 4018),
  ('MASE', '2024', '4.1.20', 'Les actions menées permettent-elles d''améliorer les résultats : Santé ?', 4, 10, 'B', false, true, 4019),
  ('MASE', '2024', '4.1.21', 'Les actions menées permettent-elles d''améliorer les résultats : Environnement ?', 4, 10, 'B', false, true, 4020),
  ('MASE', '2024', '4.2.1', 'L''employeur a-t-il mis en place un dispositif d''audits terrain SSE ?', 4, 10, 'B', false, true, 4021),
  ('MASE', '2024', '4.2.2', 'Les audits terrain SSE abordent-ils les aspects : Humains ?', 4, 10, 'B', false, true, 4022),
  ('MASE', '2024', '4.2.3', 'Les audits terrain SSE abordent-ils les aspects : Organisationnels ?', 4, 10, 'B', false, true, 4023),
  ('MASE', '2024', '4.2.4', 'Les audits terrain SSE abordent-ils les aspects : Techniques ?', 4, 10, 'B', false, true, 4024),
  ('MASE', '2024', '4.2.5', 'Les audits terrain SSE réalisés portent-ils sur le domaine : Sécurité ?', 4, 10, 'B', false, true, 4025),
  ('MASE', '2024', '4.2.6', 'Les audits terrain SSE portent-ils sur le domaine : Santé ?', 4, 10, 'B', false, true, 4026),
  ('MASE', '2024', '4.2.7', 'Les audits terrain SSE portent-ils sur le domaine : Environnement ?', 4, 10, 'B', false, true, 4027),
  ('MASE', '2024', '4.2.8', 'La fréquence de réalisation des audits terrain SSE est-elle adaptée à l''entreprise ?', 4, 50, 'V', false, true, 4028),
  ('MASE', '2024', '4.2.9', 'Ces audits terrain SSE portent-ils sur l''ensemble du personnel et des activités de l''entreprise ?', 4, 50, 'V', false, true, 4029),
  ('MASE', '2024', '4.2.10', 'Les audits terrain SSE remontent-ils des informations dans le domaine : Sécurité ?', 4, 10, 'B', false, true, 4030),
  ('MASE', '2024', '4.2.11', 'Les audits terrain SSE remontent-ils des informations dans le domaine : Santé ?', 4, 10, 'B', false, true, 4031),
  ('MASE', '2024', '4.2.12', 'Les audits terrain SSE remontent-ils des informations dans le domaine : Environnement ?', 4, 10, 'B', false, true, 4032),
  ('MASE', '2024', '4.2.13', 'Les écarts constatés lors des audits terrain SSE génèrent-ils des actions ?', 4, 40, 'V', false, true, 4033),
  ('MASE', '2024', '4.2.14', 'Ces actions sont-elles identifiées dans le(s) plan(s) d''actions SSE ?', 4, 10, 'B', false, true, 4034),
  ('MASE', '2024', '4.3.1', 'L''employeur effectue-t-il un audit de son système de management SSE au moins une fois par an ?', 4, 10, 'B', false, true, 4035),
  ('MASE', '2024', '4.3.2', 'L''audit du système de management SSE prend-il en compte l''ensemble des activités du périmètre concerné par la certification ?', 4, 50, 'V', false, true, 4036),
  ('MASE', '2024', '4.3.3', 'L''audit du système met-il en évidence des pistes de progrès ou des écarts sur : la partie documentaire ?', 4, 25, 'VD', false, true, 4037),
  ('MASE', '2024', '4.3.4', 'L''audit du système met-il en évidence des pistes de progrès ou des écarts sur : la partie terrain ?', 4, 50, 'VD', false, true, 4038),
  ('MASE', '2024', '4.3.5', 'L''audit du système permet-il de statuer sur l''atteinte de l''objectif de l''Axe 1 ?', 4, 25, 'V', false, true, 4039),
  ('MASE', '2024', '4.3.6', 'L''audit du système permet-il de statuer sur l''atteinte de l''objectif de l''Axe 2 ?', 4, 25, 'V', false, true, 4040),
  ('MASE', '2024', '4.3.7', 'L''audit du système permet-il de statuer sur l''atteinte de l''objectif de l''Axe 3 ?', 4, 50, 'V', false, true, 4041),
  ('MASE', '2024', '4.3.8', 'L''audit du système permet-il de statuer sur l''atteinte de l''objectif de l''Axe 4 ?', 4, 50, 'V', false, true, 4042),
  ('MASE', '2024', '4.3.9', 'L''audit du système permet-il de statuer sur l''atteinte de l''objectif de l''Axe 5 ?', 4, 25, 'V', false, true, 4043),
  ('MASE', '2024', '4.3.10', 'L''audit du système permet-il de vérifier que les dispositifs de l''Axe 1 sont adaptés, connus et appliqués ?', 4, 25, 'V', false, true, 4044),
  ('MASE', '2024', '4.3.11', 'L''audit du système permet-il de vérifier que les dispositifs de l''Axe 2 sont adaptés, connus et appliqués ?', 4, 25, 'V', false, true, 4045),
  ('MASE', '2024', '4.3.12', 'L''audit du système permet-il de vérifier que les dispositifs de l''Axe 3 sont adaptés, connus et appliqués ?', 4, 50, 'V', false, true, 4046),
  ('MASE', '2024', '4.3.13', 'L''audit du système permet-il de vérifier que les dispositifs de l''Axe 4 sont adaptés, connus et appliqués ?', 4, 50, 'V', false, true, 4047),
  ('MASE', '2024', '4.3.14', 'L''audit du système permet-il de vérifier que les dispositifs de l''Axe 5 sont adaptés, connus et appliqués ?', 4, 25, 'V', false, true, 4048),
  ('MASE', '2024', '4.3.15', 'Les écarts constatés lors de l''audit du système de management SSE génèrent-ils des actions ?', 4, 40, 'VD', false, true, 4049),
  ('MASE', '2024', '4.3.16', 'Ces actions sont-elles identifiées dans le(s) plan(s) d''actions SSE ?', 4, 5, 'B', false, true, 4050),
  ('MASE', '2024', '5.1.1', 'L''employeur réalise-t-il un bilan annuel de son système de management ?', 5, 10, 'B', false, true, 5000),
  ('MASE', '2024', '5.1.2', 'Ce bilan contient-il une analyse quantitative ?', 5, 10, 'B', false, true, 5001),
  ('MASE', '2024', '5.1.3', 'Ce bilan contient-il une analyse qualitative ?', 5, 10, 'B', false, true, 5002),
  ('MASE', '2024', '5.1.4', 'Ce bilan se fonde-t-il sur : l''atteinte partielle ou totale des objectifs ?', 5, 25, 'V', false, true, 5003),
  ('MASE', '2024', '5.1.5', 'Ce bilan se fonde-t-il sur : le suivi et la pertinence des indicateurs (évolution, en corrélation avec les objectifs) ?', 5, 25, 'V', false, true, 5004),
  ('MASE', '2024', '5.1.6', 'Ce bilan se fonde-t-il sur : les écarts constatés lors des vérifications de l''application de la réglementation (veille et récolement) ?', 5, 25, 'V', false, true, 5005),
  ('MASE', '2024', '5.1.7', 'Ce bilan se fonde-t-il sur : le retour des parties intéressées (représentants du personnel, service de prévention et de santé au travail, organismes de prévention, autorités…) ?', 5, 25, 'V', false, true, 5006),
  ('MASE', '2024', '5.1.8', 'Ce bilan se fonde-t-il sur : l''état d''avancement du (ou des) plan(s) d''actions et son (leur) efficacité globale ?', 5, 25, 'V', false, true, 5007),
  ('MASE', '2024', '5.1.9', 'Ce bilan se fonde-t-il sur : les modifications contractuelles et/ou réglementaires applicables à l''entreprise ?', 5, 10, 'B', false, true, 5008),
  ('MASE', '2024', '5.1.10', 'Ce bilan se fonde-t-il sur : les modifications des activités de l''entreprise ?', 5, 10, 'B', false, true, 5009),
  ('MASE', '2024', '5.1.11', 'Ce bilan se fonde-t-il sur : les remontées terrain (notamment les bonnes pratiques) dans le domaine de la Sécurité ?', 5, 30, 'V', false, true, 5010),
  ('MASE', '2024', '5.1.12', 'Ce bilan se fonde-t-il sur : les remontées terrain dans le domaine de la Santé ?', 5, 30, 'V', false, true, 5011),
  ('MASE', '2024', '5.1.13', 'Ce bilan se fonde-t-il sur : les remontées terrain dans le domaine de l''Environnement ?', 5, 30, 'V', false, true, 5012),
  ('MASE', '2024', '5.1.14', 'Ce bilan se fonde-t-il sur : le suivi des effectifs (turn-over, plan de formation et maintien des compétences) ?', 5, 25, 'V', false, true, 5013),
  ('MASE', '2024', '5.1.15', 'Ce bilan se fonde-t-il sur : les résultats de l''évaluation de la culture SSE de son personnel et des travailleurs temporaires ?', 5, 25, 'V', false, true, 5014),
  ('MASE', '2024', '5.1.16', 'Ce bilan se fonde-t-il sur : l''actualisation de l''analyse des risques et des moyens de prévention associés en fonction des évolutions d''activités ?', 5, 50, 'V', false, true, 5015),
  ('MASE', '2024', '5.1.17', 'Ce bilan se fonde-t-il sur : l''analyse des différentes modifications des conditions opératoires ?', 5, 25, 'V', false, true, 5016),
  ('MASE', '2024', '5.1.18', 'Ce bilan se fonde-t-il sur : les bilans et retours d''expérience à l''issue des tâches, travaux et prestations ?', 5, 25, 'V', false, true, 5017),
  ('MASE', '2024', '5.1.19', 'Ce bilan se fonde-t-il sur : les REx suite aux dysfonctionnements dans le domaine de la Sécurité (accidentologie) ?', 5, 25, 'V', false, true, 5018),
  ('MASE', '2024', '5.1.20', 'Ce bilan se fonde-t-il sur : les REx dans le domaine de la Santé (mesurage et exposition aux dangers, maladie professionnelle, restriction médicale) ?', 5, 25, 'V', false, true, 5019),
  ('MASE', '2024', '5.1.21', 'Ce bilan se fonde-t-il sur : les REx dans le domaine de l''Environnement (consommations, pollutions) ?', 5, 25, 'V', false, true, 5020),
  ('MASE', '2024', '5.1.22', 'Ce bilan se fonde-t-il sur : les résultats d''audits système (sur les 5 axes) et autres contrôles planifiés du système de management ?', 5, 25, 'V', false, true, 5021),
  ('MASE', '2024', '5.1.23', 'Ce bilan se fonde-t-il sur : le suivi des écarts du dernier audit de certification ?', 5, 10, 'B', true, true, 5022),
  ('MASE', '2024', '5.2.1', 'Le bilan SSE permet-il à l''employeur de faire évoluer : ses objectifs et ses indicateurs ?', 5, 80, 'VD', false, true, 5023),
  ('MASE', '2024', '5.2.2', 'Le bilan permet-il de faire évoluer : sa politique ?', 5, 25, 'VD', false, true, 5024),
  ('MASE', '2024', '5.2.3', 'Le bilan permet-il de faire évoluer : son (ou ses) plan(s) d''actions SSE, notamment issu de la conformité règlementaire ?', 5, 80, 'VD', false, true, 5025),
  ('MASE', '2024', '5.2.4', 'Le bilan permet-il de faire évoluer : ses dispositifs du système de management ?', 5, 50, 'VD', false, true, 5026),
  ('MASE', '2024', '5.2.5', 'Le bilan permet-il de faire évoluer : ses modes opératoires, analyses des risques et moyens de prévention associés ?', 5, 50, 'VD', false, true, 5027),
  ('MASE', '2024', '5.2.6', 'Le bilan permet-il de faire évoluer : l''affectation des ressources ?', 5, 20, 'VD', true, true, 5028),
  ('MASE', '2024', '5.2.7', 'Le bilan permet-il de faire évoluer : son organisation ?', 5, 20, 'VD', false, true, 5029),
  ('MASE', '2024', '5.2.8', 'Les décisions sont-elles communiquées et expliquées au personnel ?', 5, 50, 'V', true, true, 5030)
on conflict (norme, version, chapitre) do nothing;
